/************************************************************\
 **     Copyright (c) 2012-2024 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/subjects/45_enthernet/TSET_2/HX4S20_Ethernet_test/par_ph1demo/al_ip/fifo_sdr_data.v
 ** Date	:	2025 05 19
 ** TD version	:	5.6.119222
\************************************************************/

`timescale 1ns / 1ps

module fifo_sdr_data (
	rst,
	di, re, clk, we,
	do,
	empty_flag,full_flag,rdusedw,wrusedw
 
);

	input rst;
	input [23:0] di;
	input clk, we;
	input re;

	output [23:0] do;
	output empty_flag;
	output full_flag;
	output [15:0] rdusedw;
	output [15:0] wrusedw;

EG_LOGIC_RAMFIFO #(
 	.DATA_WIDTH(24),
	.ADDR_WIDTH(15),
	.SHOWAHEAD(0),
	.IMPLEMENT("AUTO")
)
logic_ramfifo(
	.rst(rst),
	.di(di),
	.clk(clk),
	.we(we),
	.do(do),
	.re(re),
	.empty_flag(empty_flag),
	.full_flag(full_flag),
	.rdusedw(rdusedw),
	.wrusedw(wrusedw)
);

endmodule