--------------------------------------------------------------
 --     Copyright (c) 2012-2024 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/subjects/45_enthernet/TSET_2/HX4S20_Ethernet_test/par_ph1demo/al_ip/fifo_sdr_data.vhd
 -- Date	:	2025 05 19
 -- TD version	:	5.6.119222
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY fifo_sdr_data IS
PORT (
	di	: IN STD_LOGIC_VECTOR(23 DOWNTO 0);

	rst	: IN STD_LOGIC;
	clk	: IN STD_LOGIC;
	we	: IN STD_LOGIC;
	re	: IN STD_LOGIC;
	do	: OUT STD_LOGIC_VECTOR(23 DOWNTO 0);
	empty_flag		: OUT STD_LOGIC;
	full_flag		: OUT STD_LOGIC;
	rdusedw			: OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
	wrusedw			: OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END fifo_sdr_data;

ARCHITECTURE struct OF fifo_sdr_data IS

	BEGIN
	inst : EG_LOGIC_RAMFIFO
		GENERIC MAP (
			DATA_WIDTH			=> 24,
			ADDR_WIDTH			=> 15,
			SHOWAHEAD			=> 0,
			IMPLEMENT			=>"AUTO"
		)
		PORT MAP (
			rst	=> rst,
			di	=> di,
			clk	=> clk,
			we	=> we,
			re	=> re,
			do	=> do,
			empty_flag	=> empty_flag,
			full_flag	=> full_flag,
			rdusedw		=> rdusedw,
			wrusedw		=> wrusedw
		);

END struct;
