--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/FPGA_prj/anloproject/HX4S20_Etherent_test_12_7/HX4S20_Ethernet_test/par_ph1demo/al_ip/ram.vhd
 -- Date	:	2023 12 14
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY ram IS
PORT (
	dob	: OUT STD_LOGIC_VECTOR(5 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(5 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(14 DOWNTO 0);
	wea	: IN STD_LOGIC;
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	addrb	: IN STD_LOGIC_VECTOR(14 DOWNTO 0);
	ceb	: IN STD_LOGIC;
	oceb	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC;
	rstb	: IN STD_LOGIC
	);
END ram;

ARCHITECTURE struct OF ram IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 6,
			DATA_WIDTH_B	=> 6,
			ADDR_WIDTH_A	=> 15,
			ADDR_WIDTH_B	=> 15,
			DATA_DEPTH_A	=> 32768,
			DATA_DEPTH_B	=> 32768,
			MODE		=> "PDPW",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "OUTREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "READBEFOREWRITE",
			RESETMODE	=> "SYNC",
			IMPLEMENT		=> "9K",
			INIT_FILE		=> "../logo.mif",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> ceb,
			clka	=> clka,
			clkb	=> clkb,
			wea	=> wea,
			bea	=> (others=>'0'),
			web	=> '0',
			beb	=> (others=>'0'),
			ocea	=> '0',
			oceb	=> oceb,
			rsta	=> '0',
			rstb	=> rstb,
			doa	=> OPEN,
			dob	=> dob
		);

END struct;
