/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/FPGA_prj/anloproject/HX4S20_Etherent_test_12_7/HX4S20_Ethernet_test/par_ph1demo/al_ip/ram.v
 ** Date	:	2023 12 14
 ** TD version	:	5.6.71036
\************************************************************/

`timescale 1ns / 1ps

module ram ( 
	dia, addra, cea, clka, wea,
	dob, addrb, ceb, oceb, clkb, rstb
);


	parameter DATA_WIDTH_A = 6; 
	parameter ADDR_WIDTH_A = 15;
	parameter DATA_DEPTH_A = 32768;
	parameter DATA_WIDTH_B = 6;
	parameter ADDR_WIDTH_B = 15;
	parameter DATA_DEPTH_B = 32768;
	parameter REGMODE_A    = "NOREG";
	parameter REGMODE_B    = "OUTREG";
	parameter WRITEMODE_A  = "NORMAL";
	parameter WRITEMODE_B  = "READBEFOREWRITE";

	output [DATA_WIDTH_B-1:0] dob;


	input  [DATA_WIDTH_A-1:0] dia;
	input  [ADDR_WIDTH_A-1:0] addra;
	input  [ADDR_WIDTH_B-1:0] addrb;
	input  wea;
	input  cea;
	input  ceb;
	input  oceb;
	input  clka;
	input  clkb;
	input  rstb;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(DATA_WIDTH_A),
				.DATA_WIDTH_B(DATA_WIDTH_B),
				.ADDR_WIDTH_A(ADDR_WIDTH_A),
				.ADDR_WIDTH_B(ADDR_WIDTH_B),
				.DATA_DEPTH_A(DATA_DEPTH_A),
				.DATA_DEPTH_B(DATA_DEPTH_B),
				.MODE("PDPW"),
				.REGMODE_A(REGMODE_A),
				.REGMODE_B(REGMODE_B),
				.WRITEMODE_A(WRITEMODE_A),
				.WRITEMODE_B(WRITEMODE_B),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("../logo.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({6{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(ceb),
				.ocea(1'b0),
				.oceb(oceb),
				.clka(clka),
				.clkb(clkb),
				.wea(wea),
				.bea(1'b0),
				.web(1'b0),
				.beb(2'b00),
				.rsta(1'b0),
				.rstb(rstb),
				.doa(),
				.dob(dob));


endmodule