--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/Projects/2023_10_10_HX4S20_test/spi_FLASH_SDRAM_pic/HX4S20/al_ip/afifo_16_256.vhd
 -- Date	:	2023 12 13
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY afifo_16_256 IS
PORT (
	di	: IN STD_LOGIC_VECTOR(15 DOWNTO 0);

	rst	: IN STD_LOGIC;
	clk	: IN STD_LOGIC;
	we	: IN STD_LOGIC;
	re	: IN STD_LOGIC;
	do	: OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
	empty_flag		: OUT STD_LOGIC;
	full_flag		: OUT STD_LOGIC;
	rdusedw			: OUT STD_LOGIC_VECTOR(8 DOWNTO 0);
	wrusedw			: OUT STD_LOGIC_VECTOR(8 DOWNTO 0)
	);
END afifo_16_256;

ARCHITECTURE struct OF afifo_16_256 IS

	BEGIN
	inst : EG_LOGIC_RAMFIFO
		GENERIC MAP (
			DATA_WIDTH			=> 16,
			ADDR_WIDTH			=> 8,
			SHOWAHEAD			=> 0,
			IMPLEMENT			=>"AUTO"
		)
		PORT MAP (
			rst	=> rst,
			di	=> di,
			clk	=> clk,
			we	=> we,
			re	=> re,
			do	=> do,
			empty_flag	=> empty_flag,
			full_flag	=> full_flag,
			rdusedw		=> rdusedw,
			wrusedw		=> wrusedw
		);

END struct;
