--------------------------------------------------------------
 --  Copyright (c) 2012-2025 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/subjects/45_enthernet/ANLO6_2/UDP_EG4_6.2/UDP_EG4_6.2/prj/UDP_EXAMPLE/al_ip/ram.vhd
 -- Date	:	2025 08 08
 -- TD version	:	6.2.168116
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY ram IS
PORT (
	dob	: OUT STD_LOGIC_VECTOR(23 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(23 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(12 DOWNTO 0);
	wea	: IN STD_LOGIC;
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	addrb	: IN STD_LOGIC_VECTOR(12 DOWNTO 0);
	clkb	: IN STD_LOGIC
	);
END ram;

ARCHITECTURE struct OF ram IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 24,
			DATA_WIDTH_B	=> 24,
			ADDR_WIDTH_A	=> 13,
			ADDR_WIDTH_B	=> 13,
			DATA_DEPTH_A	=> 8192,
			DATA_DEPTH_B	=> 8192,
			MODE		=> "PDPW",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "NOREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "NORMAL",
			RESETMODE	=> "SYNC",
			IMPLEMENT		=> "9K",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "000000000000000000000000"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> '1',
			clka	=> clka,
			clkb	=> clkb,
			wea	=> wea,
			bea	=> (others=>'0'),
			web	=> '0',
			beb	=> (others=>'0'),
			ocea	=> '0',
			oceb	=> '0',
			rsta	=> '0',
			rstb	=> '0',
			doa	=> OPEN,
			dob	=> dob
		);

END struct;
