--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/Projects/2023_10_10_HX4S20_test/VGA_hdmi_tx_display/prj/al_ip/clk_wize.vhd
 -- Date	:	2023 10 23
 -- TD version	:	5.6.71036
--------------------------------------------------------------

-------------------------------------------------------------------------------
--	Input frequency:             50.000MHz
--	Clock multiplication factor: 5
--	Clock division factor:       2
--	Clock information:
--		Clock name	| Frequency 	| Phase shift
--		C0        	| 125.000000MHZ	| 0  DEG     
--		C1        	| 25.000000 MHZ	| 0  DEG     
-------------------------------------------------------------------------------

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
USE ieee.std_logic_unsigned.ALL;
USE ieee.std_logic_arith.ALL;
LIBRARY eagle_macro;
USE eagle_macro.EAGLE_COMPONENTS.ALL;

ENTITY clk_wize IS
  PORT (
    refclk : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    clk0_out : OUT STD_LOGIC;
    clk1_out : OUT STD_LOGIC 
  );
END clk_wize;

ARCHITECTURE rtl OF clk_wize IS
  SIGNAL clk0_buf :  STD_LOGIC;
  SIGNAL fbk_wire :  STD_LOGIC;
  SIGNAL clkc_wire :  STD_LOGIC_VECTOR (4 DOWNTO 0);
BEGIN
  bufg_feedback : EG_LOGIC_BUFG
  PORT MAP (
    i => clk0_buf,
    o => fbk_wire 
  );

  pll_inst : EG_PHY_PLL
  GENERIC MAP (
    DPHASE_SOURCE => "DISABLE",
    DYNCFG => "DISABLE",
    FIN => "50.000",
    FEEDBK_MODE => "NORMAL",
    FEEDBK_PATH => "CLKC0_EXT",
    STDBY_ENABLE => "DISABLE",
    PLLRST_ENA => "ENABLE",
    SYNC_ENABLE => "DISABLE",
    GMC_GAIN => 2,
    ICP_CURRENT => 9,
    KVCO => 2,
    LPF_CAPACITOR => 1,
    LPF_RESISTOR => 8,
    REFCLK_DIV => 2,
    FBCLK_DIV => 5,
    CLKC0_ENABLE => "ENABLE",
    CLKC0_DIV => 8,
    CLKC0_CPHASE => 7,
    CLKC0_FPHASE => 0,
    CLKC1_ENABLE => "ENABLE",
    CLKC1_DIV => 40,
    CLKC1_CPHASE => 39,
    CLKC1_FPHASE => 0 
  )
  PORT MAP (
    refclk => refclk,
    reset => reset,
    stdby => '0',
    load_reg => '0',
    psclk => '0',
    psdown => '0',
    psstep => '0',
    psclksel => b"000",
    dclk => '0',
    dcs => '0',
    dwe => '0',
    di => b"00000000",
    daddr => b"000000",
    fbclk => fbk_wire,
    clkc => clkc_wire 
  );

  clk0_out <= fbk_wire;
  clk1_out <= clkc_wire(1);
  clk0_buf <= clkc_wire(0);

END rtl;

