--------------------------------------------------------------
 --  Copyright (c) 2012-2025 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/Neko/Documents/FPGA/t/al_ip/img.vhd
 -- Date	:	2025 10 17
 -- TD version	:	6.2.168116
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY img IS
PORT (
	doa		: OUT STD_LOGIC_VECTOR(15 DOWNTO 0);

	addra	: IN STD_LOGIC_VECTOR(13 DOWNTO 0);
	clka		: IN STD_LOGIC;

	dob		: OUT STD_LOGIC_VECTOR(15 DOWNTO 0);

	addrb	: IN STD_LOGIC_VECTOR(13 DOWNTO 0);
	clkb		: IN STD_LOGIC
	);
END img;

ARCHITECTURE struct OF img IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 16,
			ADDR_WIDTH_A	=> 14,
			DATA_DEPTH_A	=> 9700,
			DATA_WIDTH_B	=> 16,
			ADDR_WIDTH_B	=> 14,
			DATA_DEPTH_B	=> 9700,
			MODE			=> "DP",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "NOREG",
			IMPLEMENT	=> "32K",
			DEBUGGABLE	=> "NO",
			PACKABLE		=> "NO",
			INIT_FILE	=> "inst_data.mif.dat",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia		=> (others=>'0'),
			dib		=> (others=>'0'),
			addra	=> addra,
			addrb	=> addrb,
			cea		=> '1',
			ceb		=> '1',
			clka		=> clka,
			clkb		=> clkb,
			wea		=> '0',
			web		=> '0',
			rsta		=> '0',
			rstb		=> '0',
			doa		=> doa,
			dob		=> dob,
			ocea		=> '0',
			oceb		=> '0'
			);
END struct;
