/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/Neko/Documents/FPGA/t/al_ip/RAM03_512.v
 ** Date	:	2025 10 16
 ** TD version	:	6.2.168116
************************************************************/

`timescale 1ns / 1ps

module RAM03_512 ( 
	dia, addra, cea, clka,
	dob, addrb, ceb, oceb, clkb, rstb
);


	parameter DATA_WIDTH_A = 16; 
	parameter ADDR_WIDTH_A = 9;
	parameter DATA_DEPTH_A = 512;
	parameter DATA_WIDTH_B = 16;
	parameter ADDR_WIDTH_B = 9;
	parameter DATA_DEPTH_B = 512;
	parameter REGMODE_A    = "NOREG";
	parameter REGMODE_B    = "OUTREG";
	parameter WRITEMODE_A  = "NORMAL";
	parameter WRITEMODE_B  = "NORMAL";

	output [DATA_WIDTH_B-1:0] dob;


	input  [DATA_WIDTH_A-1:0] dia;
	input  [ADDR_WIDTH_A-1:0] addra;
	input  [ADDR_WIDTH_B-1:0] addrb;
	input  cea;
	input  ceb;
	input  oceb;
	input  clka;
	input  clkb;
	input  rstb;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(DATA_WIDTH_A),
				.DATA_WIDTH_B(DATA_WIDTH_B),
				.ADDR_WIDTH_A(ADDR_WIDTH_A),
				.ADDR_WIDTH_B(ADDR_WIDTH_B),
				.DATA_DEPTH_A(DATA_DEPTH_A),
				.DATA_DEPTH_B(DATA_DEPTH_B),
				.MODE("PDPW"),
				.REGMODE_A(REGMODE_A),
				.REGMODE_B(REGMODE_B),
				.WRITEMODE_A(WRITEMODE_A),
				.WRITEMODE_B(WRITEMODE_B),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({16{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(ceb),
				.ocea(1'b0),
				.oceb(oceb),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b1),
				.bea(1'b0),
				.web(1'b0),
				.beb(2'b00),
				.rsta(1'b0),
				.rstb(rstb),
				.doa(),
				.dob(dob));


endmodule