--------------------------------------------------------------
 --  Copyright (c) 2012-2025 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/Neko/Documents/FPGA/t/al_ip/RAM12_128.vhd
 -- Date	:	2025 10 16
 -- TD version	:	6.2.168116
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY RAM12_128 IS
PORT (
	dob	: OUT STD_LOGIC_VECTOR(11 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(11 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(6 DOWNTO 0);
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	addrb	: IN STD_LOGIC_VECTOR(6 DOWNTO 0);
	ceb	: IN STD_LOGIC;
	oceb	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC;
	rstb	: IN STD_LOGIC
	);
END RAM12_128;

ARCHITECTURE struct OF RAM12_128 IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 12,
			DATA_WIDTH_B	=> 12,
			ADDR_WIDTH_A	=> 7,
			ADDR_WIDTH_B	=> 7,
			DATA_DEPTH_A	=> 128,
			DATA_DEPTH_B	=> 128,
			MODE		=> "PDPW",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "OUTREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "NORMAL",
			RESETMODE	=> "SYNC",
			IMPLEMENT		=> "9K",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> ceb,
			clka	=> clka,
			clkb	=> clkb,
			wea	=> '1',
			bea	=> (others=>'0'),
			web	=> '0',
			beb	=> (others=>'0'),
			ocea	=> '0',
			oceb	=> oceb,
			rsta	=> '0',
			rstb	=> rstb,
			doa	=> OPEN,
			dob	=> dob
		);

END struct;
