/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/Neko/Documents/FPGA/github_anlu/video640 19fps blue chepau over/UDP_EG4_6.2/prj/UDP_EXAMPLE/al_ip/ROM_0.v
 ** Date	:	2025 11 05
 ** TD version	:	6.2.168116
************************************************************/

`timescale 1ns / 1ps

module ROM_0 ( doa, addra, clka );

	output [27:0] doa;

	input  [8:0] addra;
	input  clka;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(28),
				.ADDR_WIDTH_A(9),
				.DATA_DEPTH_A(280),
				.DATA_WIDTH_B(28),
				.ADDR_WIDTH_B(9),
				.DATA_DEPTH_B(280),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("combined_digits_dilated.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({28{1'b0}}),
				.dib({28{1'b0}}),
				.addra(addra),
				.addrb({9{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule