--------------------------------------------------------------
 --  Copyright (c) 2012-2025 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/Neko/Documents/FPGA/github_anlu/video640 19fps blue chepau over/UDP_EG4_6.2/prj/UDP_EXAMPLE/al_ip/ROM_0.vhd
 -- Date	:	2025 11 05
 -- TD version	:	6.2.168116
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY ROM_0 IS
PORT (
	doa		: OUT STD_LOGIC_VECTOR(27 DOWNTO 0);

	addra	: IN STD_LOGIC_VECTOR(8 DOWNTO 0);
	clka		: IN STD_LOGIC
	);
END ROM_0;

ARCHITECTURE struct OF ROM_0 IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 28,
			ADDR_WIDTH_A	=> 9,
			DATA_DEPTH_A	=> 280,
			DATA_WIDTH_B	=> 28,
			ADDR_WIDTH_B	=> 9,
			DATA_DEPTH_B	=> 280,
			MODE			=> "SP",
			REGMODE_A	=> "NOREG",
			IMPLEMENT	=> "9K",
			DEBUGGABLE	=> "NO",
			PACKABLE		=> "NO",
			INIT_FILE	=> "combined_digits_dilated.mif",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia		=> (others=>'0'),
			dib		=> (others=>'0'),
			addra	=> addra,
			addrb	=> (others=>'0'),
			cea		=> '1',
			ceb		=> '0',
			clka		=> clka,
			clkb		=> '0',
			web		=> '0',
			rsta		=> '0',
			rstb		=> '0',
			doa		=> doa,
			dob		=> OPEN,
			ocea		=> '0',
			oceb		=> '0'
		);

END struct;
